name: Deploy to digital ocean droplet

on:
  workflow_call:

  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Droplet and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_KEY }}
          script: |
            cd /root/5-final-let-s-get-it-over-with
            git pull origin main
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fake-it-till-you-make-it-web-app:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fake-it-till-you-make-it-ml-client:latest
            
            docker-compose down
            docker-compose up -d