name: Machine Learning CI

on:
  push:
    paths:
      - 'ml-client/**'
  pull_request:
    paths:
      - 'ml-client/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ml-client
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Build Docker image
      run: |
          docker build -t ml-client-test ./ml-client
    
    - name: Run machine-learning tests
      working-directory: ml-client
      run: PYTHONPATH=. pytest tests/