name: Machine Learning CI

on:
  push:
    paths:
      - 'ml-client/**'
  pull_request:
    paths:
      - 'ml-client/**'

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ml-client
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run machine-learning tests
        working-directory: ml-client
        run: PYTHONPATH=. pytest tests/
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build -t fake-it-till-you-make-it-ml-client:latest ./ml-client
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fake-it-till-you-make-it-ml-client:latest
      
  
  
    
