name: Web App CI

on:
  push:
    paths:
      - 'web-app/**'
  pull_request:
    paths:
      - 'web-app/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    
    - name: Install dependencies
      working-directory: web-app
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Build Docker image
      run: |
          docker build -t web-app ./web-app

    - name: Run web-app tests
      working-directory: web-app
      run: pytest tests/