name: Web App CI

on:
  push:
    paths:
      - 'web-app/**'
  pull_request:
    paths:
      - 'web-app/**'

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        working-directory: web-app
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
            docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/fake-it-till-you-make-it-web-app:latest" ./web-app
            docker push "${{ secrets.DOCKERHUB_USERNAME }}/fake-it-till-you-make-it-web-app:latest"
    
      - name: Run web-app tests
        working-directory: web-app
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DBNAME: ${{ secrets.MONGO_DBNAME }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: pytest tests/

    